### PR TITLE
Upgrade Couchbase ruby client version to 3.4.2

### PR DESCRIPTION
**Pull request by pimpin**
This should fix crashing MacOs Ruby on trying to connect on unreachable server.

### CODE REVIEW

**Comment by pimpin** [comment]
Broken with [RCBC-398](https://github.com/DemetrisChr/couchbase-ruby-client/commit/b7b601671e12a61f25f5f06d054253843929af2e#diff-7f628e510566acc50eac28d93bf0924650bb6cabe719c8fbe1a2b1e361a902c9R67)

**Comment by pimpin** [comment]
Could be fixed by next release of Couchbase ruby client with https://github.com/couchbase/couchbase-ruby-client/pull/85

**Comment by pimpin** [comment]
[Fixed](https://github.com/couchbase/couchbase-ruby-client/commit/76809d3bf9313e5d497360bba448dc0d319ea700) in master branch of Couchbase ruby client... let's wait the next release which should come 11th of april.
image

**Comment by pimpin** [comment]
Next release will come today or tomorrow...

**Review by CedricCouton — APPROVED** [review]

**Pull request merged**
